DROP TABLE IF EXISTS `query_logs_correct`;
CREATE TABLE `query_logs_correct` (
  `query` varchar(200) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

INSERT INTO segments_tester.query_logs_correct VALUES ("Zilina");
INSERT INTO segments_tester.query_logs_correct VALUES ("Bratislava");
INSERT INTO segments_tester.query_logs_correct VALUES ("Banovce nad Bebravou");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dezerice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dolne Drzkovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Horne Motesice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Radisa");
INSERT INTO segments_tester.query_logs_correct VALUES ("Rybany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Slatina nad Bebravou");
INSERT INTO segments_tester.query_logs_correct VALUES ("Svinna");
INSERT INTO segments_tester.query_logs_correct VALUES ("Sisov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Uhrovec");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velke Chlievany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Banska Bystrica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Horna Micina");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lubietova");
INSERT INTO segments_tester.query_logs_correct VALUES ("Selce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Slovenska Lupca");
INSERT INTO segments_tester.query_logs_correct VALUES ("Radvan nad Hronom");
INSERT INTO segments_tester.query_logs_correct VALUES ("Stare Hory");
INSERT INTO segments_tester.query_logs_correct VALUES ("Svaty Ondrej nad Hronom");
INSERT INTO segments_tester.query_logs_correct VALUES ("Banska Stiavnica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Batovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dolne Zemberovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dolny Almas");
INSERT INTO segments_tester.query_logs_correct VALUES ("Piarg");
INSERT INTO segments_tester.query_logs_correct VALUES ("Prensov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Pukanec");
INSERT INTO segments_tester.query_logs_correct VALUES ("Svaty Antol");
INSERT INTO segments_tester.query_logs_correct VALUES ("Bardiov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zborov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Bardiovska Nova Ves");
INSERT INTO segments_tester.query_logs_correct VALUES ("Gaboltov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hertnik");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lukov nad Teplou");
INSERT INTO segments_tester.query_logs_correct VALUES ("Malcov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Slovenska Reslavica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Uherska Reslavica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Smilno");
INSERT INTO segments_tester.query_logs_correct VALUES ("Svercov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Ceklis");
INSERT INTO segments_tester.query_logs_correct VALUES ("Most nad Grutiou");
INSERT INTO segments_tester.query_logs_correct VALUES ("Devinska Nova Ves");
INSERT INTO segments_tester.query_logs_correct VALUES ("Racistorf");
INSERT INTO segments_tester.query_logs_correct VALUES ("Stupava");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hochetetno");
INSERT INTO segments_tester.query_logs_correct VALUES ("Svaty Jur");
INSERT INTO segments_tester.query_logs_correct VALUES ("Ivanka pri Dunaji");
INSERT INTO segments_tester.query_logs_correct VALUES ("Biskupice pri Dunaji");
INSERT INTO segments_tester.query_logs_correct VALUES ("Prievoz");
INSERT INTO segments_tester.query_logs_correct VALUES ("Brezno nad Hronom");
INSERT INTO segments_tester.query_logs_correct VALUES ("Sumiac");
INSERT INTO segments_tester.query_logs_correct VALUES ("Pohorela");
INSERT INTO segments_tester.query_logs_correct VALUES ("Helpa");
INSERT INTO segments_tester.query_logs_correct VALUES ("Valaska");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hronec");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nemecka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Polhore");
INSERT INTO segments_tester.query_logs_correct VALUES ("Cierny Balog");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lom nad Hronom");
INSERT INTO segments_tester.query_logs_correct VALUES ("Myto pod Dumbierom");
INSERT INTO segments_tester.query_logs_correct VALUES ("Telgart");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lopej");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nemcar");
INSERT INTO segments_tester.query_logs_correct VALUES ("Cadca");
INSERT INTO segments_tester.query_logs_correct VALUES ("Makov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Oscadnica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Rakova");
INSERT INTO segments_tester.query_logs_correct VALUES ("Skalite");
INSERT INTO segments_tester.query_logs_correct VALUES ("Staskov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Turzovka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Visoka nad Kisucou");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zakopcie");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dobsina");
INSERT INTO segments_tester.query_logs_correct VALUES ("Slavosovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Gocovo");
INSERT INTO segments_tester.query_logs_correct VALUES ("Stitnik");
INSERT INTO segments_tester.query_logs_correct VALUES ("Rostar");
INSERT INTO segments_tester.query_logs_correct VALUES ("Rejdova");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dolny Kubin");
INSERT INTO segments_tester.query_logs_correct VALUES ("Parnica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Visny Kubin");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velicna");
INSERT INTO segments_tester.query_logs_correct VALUES ("Oravsky Podzamok");
INSERT INTO segments_tester.query_logs_correct VALUES ("Medzibrodie nad Oravou");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zazriva");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dlha nad Oravou");
INSERT INTO segments_tester.query_logs_correct VALUES ("Gelnica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Smolnik");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kosicka Bela");
INSERT INTO segments_tester.query_logs_correct VALUES ("Jaklovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kluknava");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nizny Medzev");
INSERT INTO segments_tester.query_logs_correct VALUES ("Svedlar");
INSERT INTO segments_tester.query_logs_correct VALUES ("Mnisek nad Hnilcom");
INSERT INTO segments_tester.query_logs_correct VALUES ("Giraltovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Marhan");
INSERT INTO segments_tester.query_logs_correct VALUES ("Okruhle");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hanusovce nad Toplou");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kurima");
INSERT INTO segments_tester.query_logs_correct VALUES ("Chmelov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hlohovec");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dvorniky");
INSERT INTO segments_tester.query_logs_correct VALUES ("Mestecko");
INSERT INTO segments_tester.query_logs_correct VALUES ("Versvar");
INSERT INTO segments_tester.query_logs_correct VALUES ("Trakovice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Risnovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hornie Otrokovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Maly Bab");
INSERT INTO segments_tester.query_logs_correct VALUES ("Humenne");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zavadka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Papin");
INSERT INTO segments_tester.query_logs_correct VALUES ("Koskovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Ohradzany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Snina");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kamenica nad Cirom");
INSERT INTO segments_tester.query_logs_correct VALUES ("Udavske");
INSERT INTO segments_tester.query_logs_correct VALUES ("Pcoline");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kysucke Nove Mesto");
INSERT INTO segments_tester.query_logs_correct VALUES ("Ochodnica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Meslusa");
INSERT INTO segments_tester.query_logs_correct VALUES ("Krasno nad Kys.");
INSERT INTO segments_tester.query_logs_correct VALUES ("Stara Bystrica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nova Bystrica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lovinobana");
INSERT INTO segments_tester.query_logs_correct VALUES ("Poltar");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kalimovo");
INSERT INTO segments_tester.query_logs_correct VALUES ("Uhorske");
INSERT INTO segments_tester.query_logs_correct VALUES ("Cinobana");
INSERT INTO segments_tester.query_logs_correct VALUES ("Malinec");
INSERT INTO segments_tester.query_logs_correct VALUES ("Podkrivan");
INSERT INTO segments_tester.query_logs_correct VALUES ("Tomasovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Divin");
INSERT INTO segments_tester.query_logs_correct VALUES ("Stara Halic");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kremnica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Svaty Kriz nad Hronom");
INSERT INTO segments_tester.query_logs_correct VALUES ("Trnava Hora");
INSERT INTO segments_tester.query_logs_correct VALUES ("Ladomer");
INSERT INTO segments_tester.query_logs_correct VALUES ("Jastraba");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kezmarok");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velka Lomnica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lubica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vrbov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Spisska Bela");
INSERT INTO segments_tester.query_logs_correct VALUES ("Slovenska Ves");
INSERT INTO segments_tester.query_logs_correct VALUES ("Busevce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Holumnica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zdiar");
INSERT INTO segments_tester.query_logs_correct VALUES ("Jurgov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Ilava");
INSERT INTO segments_tester.query_logs_correct VALUES ("Koseca");
INSERT INTO segments_tester.query_logs_correct VALUES ("Belusa");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dubnica nad Vahom");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zliechov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dolny Lieskov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Pruzina");
INSERT INTO segments_tester.query_logs_correct VALUES ("Krupina");
INSERT INTO segments_tester.query_logs_correct VALUES ("Domadice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hontianske Tesary");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kostolne Moravce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Bzovik");
INSERT INTO segments_tester.query_logs_correct VALUES ("Senohrad");
INSERT INTO segments_tester.query_logs_correct VALUES ("Litava");
INSERT INTO segments_tester.query_logs_correct VALUES ("Celovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nemce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Horne Byhymcine");
INSERT INTO segments_tester.query_logs_correct VALUES ("Levoca");
INSERT INTO segments_tester.query_logs_correct VALUES ("Spissky Strvtok");
INSERT INTO segments_tester.query_logs_correct VALUES ("Harhov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Spisske Pohradie");
INSERT INTO segments_tester.query_logs_correct VALUES ("Bijacovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Torysky");
INSERT INTO segments_tester.query_logs_correct VALUES ("Liptovsky Svaty Mikulas");
INSERT INTO segments_tester.query_logs_correct VALUES ("Paludzka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lipt. Hradok");
INSERT INTO segments_tester.query_logs_correct VALUES ("Liptovsky Hradok");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dovalovo");
INSERT INTO segments_tester.query_logs_correct VALUES ("Sielnica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Bobrovec");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nemecka Lupca");
INSERT INTO segments_tester.query_logs_correct VALUES ("Okolicne");
INSERT INTO segments_tester.query_logs_correct VALUES ("Huty");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hybe");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lubela");
INSERT INTO segments_tester.query_logs_correct VALUES ("Pribylina");
INSERT INTO segments_tester.query_logs_correct VALUES ("Sokolce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Strba");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vazec");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vychodna");
INSERT INTO segments_tester.query_logs_correct VALUES ("Svaty Peter");
INSERT INTO segments_tester.query_logs_correct VALUES ("Liptovske Trnovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Maluzina");
INSERT INTO segments_tester.query_logs_correct VALUES ("Malacky");
INSERT INTO segments_tester.query_logs_correct VALUES ("Borsky Svaty Jur");
INSERT INTO segments_tester.query_logs_correct VALUES ("Gajary");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hasprunka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kuchyna");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kiripolec");
INSERT INTO segments_tester.query_logs_correct VALUES ("Laksarska Nova Ves");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lozorno");
INSERT INTO segments_tester.query_logs_correct VALUES ("Moravsky Svaty Jan");
INSERT INTO segments_tester.query_logs_correct VALUES ("Plavetsky Svaty Mikulas");
INSERT INTO segments_tester.query_logs_correct VALUES ("Plavecky Stvrtok");
INSERT INTO segments_tester.query_logs_correct VALUES ("Solosnica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Uhorska Ves");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velke Levare");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zavod");
INSERT INTO segments_tester.query_logs_correct VALUES ("Medzilaborce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Habure");
INSERT INTO segments_tester.query_logs_correct VALUES ("Havaj");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vyrava");
INSERT INTO segments_tester.query_logs_correct VALUES ("Visnia Radvan");
INSERT INTO segments_tester.query_logs_correct VALUES ("Niznia Olka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Krasny Brod");
INSERT INTO segments_tester.query_logs_correct VALUES ("Michalovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Malcice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Budkovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Palin");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vysnie Revistia");
INSERT INTO segments_tester.query_logs_correct VALUES ("Pavlovce nad Uhom");
INSERT INTO segments_tester.query_logs_correct VALUES ("Rakovec nad Ondavou");
INSERT INTO segments_tester.query_logs_correct VALUES ("Stare");
INSERT INTO segments_tester.query_logs_correct VALUES ("/T");
INSERT INTO segments_tester.query_logs_correct VALUES ("Krivostany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zbudza");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vinna");
INSERT INTO segments_tester.query_logs_correct VALUES ("Strazske");
INSERT INTO segments_tester.query_logs_correct VALUES ("Pozdisovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vrbovec");
INSERT INTO segments_tester.query_logs_correct VALUES ("Ubrez");
INSERT INTO segments_tester.query_logs_correct VALUES ("Male Zaluzice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lucky");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velke Zaluzice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hazin");
INSERT INTO segments_tester.query_logs_correct VALUES ("Banovce nad Ondavou");
INSERT INTO segments_tester.query_logs_correct VALUES ("Jovsa");
INSERT INTO segments_tester.query_logs_correct VALUES ("Modra");
INSERT INTO segments_tester.query_logs_correct VALUES ("Casta");
INSERT INTO segments_tester.query_logs_correct VALUES ("Pudmerice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Bahoni");
INSERT INTO segments_tester.query_logs_correct VALUES ("Pezinok");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velke Senkvice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nemecky Grob");
INSERT INTO segments_tester.query_logs_correct VALUES ("Modry Kamen");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dolne Strhary");
INSERT INTO segments_tester.query_logs_correct VALUES ("Senne");
INSERT INTO segments_tester.query_logs_correct VALUES ("Sklabina");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dolna Strehova");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dolne Plachtince");
INSERT INTO segments_tester.query_logs_correct VALUES ("Turie Pole");
INSERT INTO segments_tester.query_logs_correct VALUES ("Myjava");
INSERT INTO segments_tester.query_logs_correct VALUES ("Brezova nad Bradlom");
INSERT INTO segments_tester.query_logs_correct VALUES ("Tura Luka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kostolne");
INSERT INTO segments_tester.query_logs_correct VALUES ("Krajne");
INSERT INTO segments_tester.query_logs_correct VALUES ("Namestovo");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zakamene");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vesele");
INSERT INTO segments_tester.query_logs_correct VALUES ("Rabca");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lokca");
INSERT INTO segments_tester.query_logs_correct VALUES ("Erdulka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Krusetnica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hrustin");
INSERT INTO segments_tester.query_logs_correct VALUES ("Slanica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nova Bana");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zarnovica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Rybnik");
INSERT INTO segments_tester.query_logs_correct VALUES ("Cajkov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Svaty Benedik");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velke Pole");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hrabico");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hlinik nad Hr.");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hvozdnica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Stary Tekov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vyhne");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nove Mesto nad Vahom");
INSERT INTO segments_tester.query_logs_correct VALUES ("Beckov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Cachtice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hradok");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lubina");
INSERT INTO segments_tester.query_logs_correct VALUES ("Moravske Lieskove");
INSERT INTO segments_tester.query_logs_correct VALUES ("Pobedim");
INSERT INTO segments_tester.query_logs_correct VALUES ("Podolie");
INSERT INTO segments_tester.query_logs_correct VALUES ("Stara Tura");
INSERT INTO segments_tester.query_logs_correct VALUES ("Svaty Kriz nad Vahom");
INSERT INTO segments_tester.query_logs_correct VALUES ("Piestany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Chtelnica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Drahovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Banka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Krakovany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velke Kostolany");
INSERT INTO segments_tester.query_logs_correct VALUES ("/Vrbove");
INSERT INTO segments_tester.query_logs_correct VALUES ("Poprad");
INSERT INTO segments_tester.query_logs_correct VALUES ("Spisska Sobota");
INSERT INTO segments_tester.query_logs_correct VALUES ("Batizovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kubachy");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lucivna");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hranovnica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Straza");
INSERT INTO segments_tester.query_logs_correct VALUES ("Povazska Bystrica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Domaniza");
INSERT INTO segments_tester.query_logs_correct VALUES ("Marikova");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velka Udica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Presov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Bogdanovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Klembarok");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kysak");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kapusany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Meretica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kostolany nad Hor.");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lemesany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velky Saris");
INSERT INTO segments_tester.query_logs_correct VALUES ("Sarisske Luky");
INSERT INTO segments_tester.query_logs_correct VALUES ("Svinia");
INSERT INTO segments_tester.query_logs_correct VALUES ("Siroke");
INSERT INTO segments_tester.query_logs_correct VALUES ("Rozhanovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Tubrina");
INSERT INTO segments_tester.query_logs_correct VALUES ("Solivar");
INSERT INTO segments_tester.query_logs_correct VALUES ("Tulcik");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kec. Peklany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Prievidza");
INSERT INTO segments_tester.query_logs_correct VALUES ("Bojnice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Novaky");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nedozery");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nitrianske Rudno");
INSERT INTO segments_tester.query_logs_correct VALUES ("Oslany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Racice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Diviaky nad Nitricou");
INSERT INTO segments_tester.query_logs_correct VALUES ("Bystricany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velka Causa");
INSERT INTO segments_tester.query_logs_correct VALUES ("Handlova");
INSERT INTO segments_tester.query_logs_correct VALUES ("Puchov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Bolesov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Luky");
INSERT INTO segments_tester.query_logs_correct VALUES ("Cerveny Kamen");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lednicke Rovne");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lednica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dohnany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zariecie");
INSERT INTO segments_tester.query_logs_correct VALUES ("Pruske");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lazy pod Makytou");
INSERT INTO segments_tester.query_logs_correct VALUES ("Revuca");
INSERT INTO segments_tester.query_logs_correct VALUES ("Muran");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lubenik");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kamenany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Sirk");
INSERT INTO segments_tester.query_logs_correct VALUES ("Ratkova");
INSERT INTO segments_tester.query_logs_correct VALUES ("Ruzomberok");
INSERT INTO segments_tester.query_logs_correct VALUES ("Liptovske Revuce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Liptovska Luzna");
INSERT INTO segments_tester.query_logs_correct VALUES ("Likavka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Liptovska Tepla");
INSERT INTO segments_tester.query_logs_correct VALUES ("Liptovska Stiavnica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Liptovska Osada");
INSERT INTO segments_tester.query_logs_correct VALUES ("Liskova");
INSERT INTO segments_tester.query_logs_correct VALUES ("Gombas");
INSERT INTO segments_tester.query_logs_correct VALUES ("Sabinov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Sarisske Dravce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Circ");
INSERT INTO segments_tester.query_logs_correct VALUES ("Plavec nad Popradom");
INSERT INTO segments_tester.query_logs_correct VALUES ("Bertotovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Michalany nad Torysou");
INSERT INTO segments_tester.query_logs_correct VALUES ("Terna");
INSERT INTO segments_tester.query_logs_correct VALUES ("Pecovska Nova Ves");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lipiany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Brezovica nad Tor.");
INSERT INTO segments_tester.query_logs_correct VALUES ("Senica nad Myjavou");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dojc");
INSERT INTO segments_tester.query_logs_correct VALUES ("Jablonica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Cerova - Lieskove");
INSERT INTO segments_tester.query_logs_correct VALUES ("Cacov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Straze nad Myjavou");
INSERT INTO segments_tester.query_logs_correct VALUES ("Sastin");
INSERT INTO segments_tester.query_logs_correct VALUES ("Sabotiste");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vrbovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Borsky Svaty Mikulas");
INSERT INTO segments_tester.query_logs_correct VALUES ("Sotina");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hlboke");
INSERT INTO segments_tester.query_logs_correct VALUES ("Skalica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kopcany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kuty");
INSERT INTO segments_tester.query_logs_correct VALUES ("Petrova Ves");
INSERT INTO segments_tester.query_logs_correct VALUES ("Radosovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Brodske");
INSERT INTO segments_tester.query_logs_correct VALUES ("Gbely");
INSERT INTO segments_tester.query_logs_correct VALUES ("Unin");
INSERT INTO segments_tester.query_logs_correct VALUES ("Holic");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vradiste");
INSERT INTO segments_tester.query_logs_correct VALUES ("Spisska Nova Ves");
INSERT INTO segments_tester.query_logs_correct VALUES ("Markusovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Koterbachy");
INSERT INTO segments_tester.query_logs_correct VALUES ("Spisske Vlachy");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hrabusice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Letanovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Spissky Hrusov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Krompachy");
INSERT INTO segments_tester.query_logs_correct VALUES ("Spissky Vlachoch");
INSERT INTO segments_tester.query_logs_correct VALUES ("Stara Lubovna");
INSERT INTO segments_tester.query_logs_correct VALUES ("Podolinec");
INSERT INTO segments_tester.query_logs_correct VALUES ("Mnisek nad Popradom");
INSERT INTO segments_tester.query_logs_correct VALUES ("Maly Lipnik");
INSERT INTO segments_tester.query_logs_correct VALUES ("Gnazda");
INSERT INTO segments_tester.query_logs_correct VALUES ("Plavnica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Stropkov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Krajna Polana");
INSERT INTO segments_tester.query_logs_correct VALUES ("Breznicka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nizna Olsava");
INSERT INTO segments_tester.query_logs_correct VALUES ("Visny Svidnik");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kapisov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Iadomirova");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hrabovcik");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vysny Orlik");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kosarovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Krajna Porubka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Trebisov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Secovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Herlany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Parchoviany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kuzmice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Bidovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Slanec");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vojcice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velaty");
INSERT INTO segments_tester.query_logs_correct VALUES ("Trencin");
INSERT INTO segments_tester.query_logs_correct VALUES ("Trencianske Teplice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nemsova");
INSERT INTO segments_tester.query_logs_correct VALUES ("Istebnik");
INSERT INTO segments_tester.query_logs_correct VALUES ("Drietoma");
INSERT INTO segments_tester.query_logs_correct VALUES ("Melcice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Bosaca");
INSERT INTO segments_tester.query_logs_correct VALUES ("Sedlicna");
INSERT INTO segments_tester.query_logs_correct VALUES ("Trencanska Tepla");
INSERT INTO segments_tester.query_logs_correct VALUES ("Topolcany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Tovarniky");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velke Bielice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Simonovany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Bojna");
INSERT INTO segments_tester.query_logs_correct VALUES ("Klatova Nova Ves");
INSERT INTO segments_tester.query_logs_correct VALUES ("Bosany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Horne Obdiekovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Chynorany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velke Uherce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Prasice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Preselany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zabokreky nad Nitrou");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kovarce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Ludanice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Krusovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Trnava");
INSERT INTO segments_tester.query_logs_correct VALUES ("Sered");
INSERT INTO segments_tester.query_logs_correct VALUES ("Sintava");
INSERT INTO segments_tester.query_logs_correct VALUES ("Smolenice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Spacince");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velke Surovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Voderady");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zavar");
INSERT INTO segments_tester.query_logs_correct VALUES ("Abraham");
INSERT INTO segments_tester.query_logs_correct VALUES ("Bohunice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Boleraz");
INSERT INTO segments_tester.query_logs_correct VALUES ("Cifer");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dehtice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dolna Krupa");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dolna Streda nad Vahom");
INSERT INTO segments_tester.query_logs_correct VALUES ("Horne Oresany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Majcichov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Krestar");
INSERT INTO segments_tester.query_logs_correct VALUES ("Modranka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nadas");
INSERT INTO segments_tester.query_logs_correct VALUES ("Pusty Fedymes");
INSERT INTO segments_tester.query_logs_correct VALUES ("Rozindol");
INSERT INTO segments_tester.query_logs_correct VALUES ("Trstena");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vysna Zubrica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Jablonka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Niznia nad Oravou");
INSERT INTO segments_tester.query_logs_correct VALUES (" /T");
INSERT INTO segments_tester.query_logs_correct VALUES ("Podbiel");
INSERT INTO segments_tester.query_logs_correct VALUES ("Ustie nad Oravou");
INSERT INTO segments_tester.query_logs_correct VALUES ("Pobelnik");
INSERT INTO segments_tester.query_logs_correct VALUES ("Podvlk");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nizna Lipnica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Tvrdosin");
INSERT INTO segments_tester.query_logs_correct VALUES ("Liesek");
INSERT INTO segments_tester.query_logs_correct VALUES ("Turciansky Svaty Martin");
INSERT INTO segments_tester.query_logs_correct VALUES ("Turany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Sucany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vrutky");
INSERT INTO segments_tester.query_logs_correct VALUES ("Priekopa");
INSERT INTO segments_tester.query_logs_correct VALUES ("Horne Jaseno");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kostany nad Turcom");
INSERT INTO segments_tester.query_logs_correct VALUES ("Necpaly");
INSERT INTO segments_tester.query_logs_correct VALUES ("Maly Cepcin");
INSERT INTO segments_tester.query_logs_correct VALUES ("Mosovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Slovenske Pravno");
INSERT INTO segments_tester.query_logs_correct VALUES ("Stubove Teplice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Pribovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Klastor pod Znievom");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velka Bytca");
INSERT INTO segments_tester.query_logs_correct VALUES ("Stavnik");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dolny Hricov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velke Rovne");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zemanska Kotesova");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kolarovice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Predmier");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zlate Moravce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kozarovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Gymes");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hostovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Cierne Klucany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nova Ves nad Zitavou");
INSERT INTO segments_tester.query_logs_correct VALUES ("Male Vozokany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Tesary nad Zitavou");
INSERT INTO segments_tester.query_logs_correct VALUES ("Topolcianky");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dolnie Slazany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Obyce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Neverice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zvolen");
INSERT INTO segments_tester.query_logs_correct VALUES ("Detva");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dobra Niva");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hajniky");
INSERT INTO segments_tester.query_logs_correct VALUES ("Ocova");
INSERT INTO segments_tester.query_logs_correct VALUES ("Pliesovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Sasa");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zvolenska Slatina");
INSERT INTO segments_tester.query_logs_correct VALUES ("Budce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Rajec");
INSERT INTO segments_tester.query_logs_correct VALUES ("Budatin");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lietavska Lutca");
INSERT INTO segments_tester.query_logs_correct VALUES ("Varin");
INSERT INTO segments_tester.query_logs_correct VALUES ("Rosina");
INSERT INTO segments_tester.query_logs_correct VALUES ("Terchova");
INSERT INTO segments_tester.query_logs_correct VALUES ("Rajecke Teplice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Cicmany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vyhne Labor Camp");
INSERT INTO segments_tester.query_logs_correct VALUES ("Ustredna Zidov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zilina");
INSERT INTO segments_tester.query_logs_correct VALUES ("Bratislava");
INSERT INTO segments_tester.query_logs_correct VALUES ("Banovce nad Bebravou");
INSERT INTO segments_tester.query_logs_correct VALUES ("Banska Bystrica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Banska Stiavnica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Bardiov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Brezno nad Hronom");
INSERT INTO segments_tester.query_logs_correct VALUES ("Cadca");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dobsina");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dolny Kubin");
INSERT INTO segments_tester.query_logs_correct VALUES ("Gelnica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Giraltovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hlohovec");
INSERT INTO segments_tester.query_logs_correct VALUES ("Humenne");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kysucke Nove Mesto");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lovinobana");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kremnica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kezmarok");
INSERT INTO segments_tester.query_logs_correct VALUES ("Ilava");
INSERT INTO segments_tester.query_logs_correct VALUES ("Krupina");
INSERT INTO segments_tester.query_logs_correct VALUES ("Levoca");
INSERT INTO segments_tester.query_logs_correct VALUES ("Liptovsky Svaty Mikulas");
INSERT INTO segments_tester.query_logs_correct VALUES ("Malacky");
INSERT INTO segments_tester.query_logs_correct VALUES ("Medzilaborce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Michalovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Modra");
INSERT INTO segments_tester.query_logs_correct VALUES ("Modry Kamen");
INSERT INTO segments_tester.query_logs_correct VALUES ("Myjava");
INSERT INTO segments_tester.query_logs_correct VALUES ("Namestovo");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nova Bana");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nove Mesto nad Vahom");
INSERT INTO segments_tester.query_logs_correct VALUES ("Piestany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Poprad");
INSERT INTO segments_tester.query_logs_correct VALUES ("Povazska Bystrica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Presov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Prievidza");
INSERT INTO segments_tester.query_logs_correct VALUES ("Puchov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Revuca");
INSERT INTO segments_tester.query_logs_correct VALUES ("Ruzomberok");
INSERT INTO segments_tester.query_logs_correct VALUES ("Sabinov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Senica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Skalica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Spisska Nova Ves");
INSERT INTO segments_tester.query_logs_correct VALUES ("Stara Lubovna");
INSERT INTO segments_tester.query_logs_correct VALUES ("Stropkov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Trebisov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Trencin");
INSERT INTO segments_tester.query_logs_correct VALUES ("Topolcany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Trnava");
INSERT INTO segments_tester.query_logs_correct VALUES ("Trstena");
INSERT INTO segments_tester.query_logs_correct VALUES ("Turciansky Svaty Martin");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velka Bytca");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zlate Moravce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zvolen");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vyhne (Tabor)");
INSERT INTO segments_tester.query_logs_correct VALUES ("Various places (to be established - very few)");
INSERT INTO segments_tester.query_logs_correct VALUES ("Ustredna Zidov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Slovakia");
INSERT INTO segments_tester.query_logs_correct VALUES ("Work Camps in Zilina county (Documented by the HG)");
INSERT INTO segments_tester.query_logs_correct VALUES ("Jews in custody in Bratislava in Sept 1942");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hornany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dubodiel a Cuklasovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zitna");
INSERT INTO segments_tester.query_logs_correct VALUES ("Male Ostratice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velke Ostratice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nedasovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Slatina nad Bebravou");
INSERT INTO segments_tester.query_logs_correct VALUES ("Cierna Lehota");
INSERT INTO segments_tester.query_logs_correct VALUES ("Timoradza");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velka Hradna");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velke Chlievany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Pocenany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Biskupice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nemce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Radvan nad Hronom");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kremnicka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kralova");
INSERT INTO segments_tester.query_logs_correct VALUES ("Malachov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Medzibrod nad Hronom");
INSERT INTO segments_tester.query_logs_correct VALUES ("Piarg");
INSERT INTO segments_tester.query_logs_correct VALUES ("Pocuradlo");
INSERT INTO segments_tester.query_logs_correct VALUES ("Prensov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Prensov Badan");
INSERT INTO segments_tester.query_logs_correct VALUES ("Bardiovska Nova Ves");
INSERT INTO segments_tester.query_logs_correct VALUES ("Andrejov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Belovez");
INSERT INTO segments_tester.query_logs_correct VALUES ("Komarov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Ortutov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Sasov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Gaboltov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Cigelka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Pricka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kurov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Petrov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Slovenska Reslavica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Janovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Trocany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Abranovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Smilno");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hutka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Niznia Polanka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vistnia Polanka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Niklova");
INSERT INTO segments_tester.query_logs_correct VALUES ("Police Headquarters in Bratislava");
INSERT INTO segments_tester.query_logs_correct VALUES ("Police Headquarters in Bratislava (continued)");
INSERT INTO segments_tester.query_logs_correct VALUES ("Devinska Nova Ves");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lamac");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dubravka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Ivanka pri Dunaji");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vajnory");
INSERT INTO segments_tester.query_logs_correct VALUES ("Biskupice pri Dunaji");
INSERT INTO segments_tester.query_logs_correct VALUES ("Verekne");
INSERT INTO segments_tester.query_logs_correct VALUES ("Mast");
INSERT INTO segments_tester.query_logs_correct VALUES ("Prievoz");
INSERT INTO segments_tester.query_logs_correct VALUES ("Karlova Ves");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hronec");
INSERT INTO segments_tester.query_logs_correct VALUES ("Osrblie");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dulvina");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lom nad Hronom");
INSERT INTO segments_tester.query_logs_correct VALUES ("Drabsko");
INSERT INTO segments_tester.query_logs_correct VALUES ("Sitla");
INSERT INTO segments_tester.query_logs_correct VALUES ("Helpa");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zavadka nad Hronom");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dubora");
INSERT INTO segments_tester.query_logs_correct VALUES ("Skalite");
INSERT INTO segments_tester.query_logs_correct VALUES ("Cierne");
INSERT INTO segments_tester.query_logs_correct VALUES ("Svrcinovec");
INSERT INTO segments_tester.query_logs_correct VALUES ("Staskov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Olesna");
INSERT INTO segments_tester.query_logs_correct VALUES ("Podvysoka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Stitnik");
INSERT INTO segments_tester.query_logs_correct VALUES ("Roznavske Bystre");
INSERT INTO segments_tester.query_logs_correct VALUES ("Rozlozna");
INSERT INTO segments_tester.query_logs_correct VALUES ("Genc");
INSERT INTO segments_tester.query_logs_correct VALUES ("Rostar");
INSERT INTO segments_tester.query_logs_correct VALUES ("Petrmanovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hankova");
INSERT INTO segments_tester.query_logs_correct VALUES ("Brdarska");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kralovany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velky Bysterec");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dolnia Lehota");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hornia Lehota");
INSERT INTO segments_tester.query_logs_correct VALUES ("Bzimy");
INSERT INTO segments_tester.query_logs_correct VALUES ("Gelnica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zakarovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Holomanovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Smolnik");
INSERT INTO segments_tester.query_logs_correct VALUES ("Uhorna");
INSERT INTO segments_tester.query_logs_correct VALUES ("Smolnicka Huta");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kosicke Hamry");
INSERT INTO segments_tester.query_logs_correct VALUES ("Jaklovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kojsov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Margecany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velky Folkmar");
INSERT INTO segments_tester.query_logs_correct VALUES ("Stos");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nizny Medzev");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hanusovce nad Toplou");
INSERT INTO segments_tester.query_logs_correct VALUES ("Bystre nad Toplou");
INSERT INTO segments_tester.query_logs_correct VALUES ("Bystra");
INSERT INTO segments_tester.query_logs_correct VALUES ("Durdos");
INSERT INTO segments_tester.query_logs_correct VALUES ("Harmanovce nad Toplou");
INSERT INTO segments_tester.query_logs_correct VALUES ("Mataska");
INSERT INTO segments_tester.query_logs_correct VALUES ("Petrovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Remeniny");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vavrinec");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vlaca");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kurima");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dubinne");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kucin");
INSERT INTO segments_tester.query_logs_correct VALUES ("Madunice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zlkovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("/-T");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lukacovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Pastuchov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dolne Vasardice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Merasice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Trakovice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Bucany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Melzenice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Maly Bab");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velky Bab");
INSERT INTO segments_tester.query_logs_correct VALUES ("Rumanova");
INSERT INTO segments_tester.query_logs_correct VALUES ("Pusta Kert");
INSERT INTO segments_tester.query_logs_correct VALUES ("Humenne");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kochanovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kudlovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zavadka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lieskovec");
INSERT INTO segments_tester.query_logs_correct VALUES ("Myslina");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hudcovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Topolovka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Brakov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Koskovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Jablon");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hankovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zbudske Dlhe");
INSERT INTO segments_tester.query_logs_correct VALUES ("Humensky Rokitov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zbudsky Rokytov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Snina");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dlhe nad Cir");
INSERT INTO segments_tester.query_logs_correct VALUES ("Bela nad Cir");
INSERT INTO segments_tester.query_logs_correct VALUES ("Udavske");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vysny Hrusov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lubisa");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nizne Ladiskovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Pcoline");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hostovice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Cukalovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Krasno nad Kys.");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zborov nad Bystr.");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lovinobana");
INSERT INTO segments_tester.query_logs_correct VALUES ("Uderina");
INSERT INTO segments_tester.query_logs_correct VALUES ("Mytna");
INSERT INTO segments_tester.query_logs_correct VALUES ("Poltar");
INSERT INTO segments_tester.query_logs_correct VALUES ("Ceske Brezovo");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kalimovo");
INSERT INTO segments_tester.query_logs_correct VALUES ("Breznicka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zelene");
INSERT INTO segments_tester.query_logs_correct VALUES ("Uhorske");
INSERT INTO segments_tester.query_logs_correct VALUES ("Bystricka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Krna");
INSERT INTO segments_tester.query_logs_correct VALUES ("Divin");
INSERT INTO segments_tester.query_logs_correct VALUES ("Ruzina");
INSERT INTO segments_tester.query_logs_correct VALUES ("Tuhar");
INSERT INTO segments_tester.query_logs_correct VALUES ("Stara Halic");
INSERT INTO segments_tester.query_logs_correct VALUES ("Luborec");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kezmarok");
INSERT INTO segments_tester.query_logs_correct VALUES ("Starzky nad Popradom");
INSERT INTO segments_tester.query_logs_correct VALUES ("Rakusy");
INSERT INTO segments_tester.query_logs_correct VALUES ("Maly Slavkov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Huncovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Stara Lesna");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vrbov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Farkasovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zakovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Slovenska Ves");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lendak");
INSERT INTO segments_tester.query_logs_correct VALUES ("Koseca");
INSERT INTO segments_tester.query_logs_correct VALUES ("Ladce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Belusa");
INSERT INTO segments_tester.query_logs_correct VALUES ("Visolaje");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hloza");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dubnica nad Vahom");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velky Kolacin");
INSERT INTO segments_tester.query_logs_correct VALUES ("Slopna");
INSERT INTO segments_tester.query_logs_correct VALUES ("Podskalie");
INSERT INTO segments_tester.query_logs_correct VALUES ("Horny Lieskov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Bzovik");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dolnie Mladonice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Celovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hrusov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Horne Byhymcine");
INSERT INTO segments_tester.query_logs_correct VALUES ("Medovarce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Levoca");
INSERT INTO segments_tester.query_logs_correct VALUES ("Iliasovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Spissky Strvtok");
INSERT INTO segments_tester.query_logs_correct VALUES ("Machalovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Stavce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Abrahamovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dravce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Harhov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Domanovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Spisske Pohradie");
INSERT INTO segments_tester.query_logs_correct VALUES ("Baldovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vis. Stavkov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Grane Petrovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Liptovsky Hradok");
INSERT INTO segments_tester.query_logs_correct VALUES ("Porubka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Podturen");
INSERT INTO segments_tester.query_logs_correct VALUES ("Ondrasova");
INSERT INTO segments_tester.query_logs_correct VALUES ("Sokolce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vlachy");
INSERT INTO segments_tester.query_logs_correct VALUES ("Raztoky");
INSERT INTO segments_tester.query_logs_correct VALUES ("Borsky Svaty Jur");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kuklov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kuchyna");
INSERT INTO segments_tester.query_logs_correct VALUES ("Pernek");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kiripolec");
INSERT INTO segments_tester.query_logs_correct VALUES ("Jakubov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Laksarska Nova Ves");
INSERT INTO segments_tester.query_logs_correct VALUES ("Niklasov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Moravsky Svaty Jan");
INSERT INTO segments_tester.query_logs_correct VALUES ("Sekule");
INSERT INTO segments_tester.query_logs_correct VALUES ("Plavecky Stvrtok");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lab");
INSERT INTO segments_tester.query_logs_correct VALUES ("Solosnica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Rarbok");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velke Levare");
INSERT INTO segments_tester.query_logs_correct VALUES ("Male Levare");
INSERT INTO segments_tester.query_logs_correct VALUES ("Medzilaborce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kalinov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vydran");
INSERT INTO segments_tester.query_logs_correct VALUES ("Habure");
INSERT INTO segments_tester.query_logs_correct VALUES ("Borov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Certizne");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vyrava");
INSERT INTO segments_tester.query_logs_correct VALUES ("Cabalovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vilagy");
INSERT INTO segments_tester.query_logs_correct VALUES ("Visnie Zbojne");
INSERT INTO segments_tester.query_logs_correct VALUES ("Niznie Zbojne");
INSERT INTO segments_tester.query_logs_correct VALUES ("Visnia Radvan");
INSERT INTO segments_tester.query_logs_correct VALUES ("Niznia Radvan");
INSERT INTO segments_tester.query_logs_correct VALUES ("Brestov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hrubov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hrabovec");
INSERT INTO segments_tester.query_logs_correct VALUES ("Krasny Brod");
INSERT INTO segments_tester.query_logs_correct VALUES ("Sukov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Niznie Cabiny");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vysnie Cabiny");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nagov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Malcice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Markovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Petrikovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Budkovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hatalov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Slavkovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Sliepkovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vysnie Revistia");
INSERT INTO segments_tester.query_logs_correct VALUES ("Blatne Revistia");
INSERT INTO segments_tester.query_logs_correct VALUES ("Pavlovce nad Uhom");
INSERT INTO segments_tester.query_logs_correct VALUES ("Tegena");
INSERT INTO segments_tester.query_logs_correct VALUES ("Cierne Pole");
INSERT INTO segments_tester.query_logs_correct VALUES ("Visoka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Rakovec nad Ondavou");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lesne");
INSERT INTO segments_tester.query_logs_correct VALUES ("Moraviany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nizny Hrusov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Suche");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vinna");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kaluza");
INSERT INTO segments_tester.query_logs_correct VALUES ("Tarnava");
INSERT INTO segments_tester.query_logs_correct VALUES ("Strazske");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vola");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nacina Ves");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vrbovec");
INSERT INTO segments_tester.query_logs_correct VALUES ("Cecehov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Inacovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Jastrable");
INSERT INTO segments_tester.query_logs_correct VALUES ("Krasok");
INSERT INTO segments_tester.query_logs_correct VALUES ("Rebrin");
INSERT INTO segments_tester.query_logs_correct VALUES ("Ubrez");
INSERT INTO segments_tester.query_logs_correct VALUES ("Fekisovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hnojne");
INSERT INTO segments_tester.query_logs_correct VALUES ("Gajdos");
INSERT INTO segments_tester.query_logs_correct VALUES ("Banovce nad Ondavou");
INSERT INTO segments_tester.query_logs_correct VALUES ("Bracovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Falkusovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Racanov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Laskovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lozin");
INSERT INTO segments_tester.query_logs_correct VALUES ("Trhoviste");
INSERT INTO segments_tester.query_logs_correct VALUES ("Jovsa");
INSERT INTO segments_tester.query_logs_correct VALUES ("Klokocov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nemecka Poruba");
INSERT INTO segments_tester.query_logs_correct VALUES ("Casta");
INSERT INTO segments_tester.query_logs_correct VALUES ("Durova");
INSERT INTO segments_tester.query_logs_correct VALUES ("Pila");
INSERT INTO segments_tester.query_logs_correct VALUES ("Sarfia");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dobova");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nemecky Grob");
INSERT INTO segments_tester.query_logs_correct VALUES ("Cataj");
INSERT INTO segments_tester.query_logs_correct VALUES ("Modry Kamen");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velky Krtys");
INSERT INTO segments_tester.query_logs_correct VALUES ("Maly Krtys");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dolne Strhary");
INSERT INTO segments_tester.query_logs_correct VALUES ("Potor");
INSERT INTO segments_tester.query_logs_correct VALUES ("Horna Strehova");
INSERT INTO segments_tester.query_logs_correct VALUES ("Sklabina");
INSERT INTO segments_tester.query_logs_correct VALUES ("Obeckov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nova Ves");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dolna Strehova");
INSERT INTO segments_tester.query_logs_correct VALUES ("Slovenske Klacany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Chrtany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dolne Plachtince");
INSERT INTO segments_tester.query_logs_correct VALUES ("Stredne Plachtince");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dolne Pribelce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zakamene");
INSERT INTO segments_tester.query_logs_correct VALUES ("Novot");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vesele");
INSERT INTO segments_tester.query_logs_correct VALUES ("Mutne");
INSERT INTO segments_tester.query_logs_correct VALUES ("Rabca");
INSERT INTO segments_tester.query_logs_correct VALUES ("Sikelce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Slanica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Klin");
INSERT INTO segments_tester.query_logs_correct VALUES ("Bobrov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zubrohlava");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nova Bana");
INSERT INTO segments_tester.query_logs_correct VALUES ("Brehy");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zupkov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Stary Tekov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Klacany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velke Kozmalovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vyhne");
INSERT INTO segments_tester.query_logs_correct VALUES ("Rapiste");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nove Mesto nad Vahom");
INSERT INTO segments_tester.query_logs_correct VALUES ("Mnesice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Beckov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kalnica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kocovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nova Ves nad Vahom");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vieska Beckovska");
INSERT INTO segments_tester.query_logs_correct VALUES ("Horka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Luka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Stara Lehota");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dolne Bzince");
INSERT INTO segments_tester.query_logs_correct VALUES ("Horne Bzince");
INSERT INTO segments_tester.query_logs_correct VALUES ("Moravske Lieskove");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dolne Srnie");
INSERT INTO segments_tester.query_logs_correct VALUES ("Pobedim");
INSERT INTO segments_tester.query_logs_correct VALUES ("Basovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Horna Streda");
INSERT INTO segments_tester.query_logs_correct VALUES ("Korytne");
INSERT INTO segments_tester.query_logs_correct VALUES ("Castkovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Svaty Kriz nad Vahom");
INSERT INTO segments_tester.query_logs_correct VALUES ("Brunovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Viaska Potvorice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Straze");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velke Kostolany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Pecenady");
INSERT INTO segments_tester.query_logs_correct VALUES ("Spisska Sobota");
INSERT INTO segments_tester.query_logs_correct VALUES ("Stola");
INSERT INTO segments_tester.query_logs_correct VALUES ("Batizovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Milbach");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nova Lesna");
INSERT INTO segments_tester.query_logs_correct VALUES ("Visna Sunava");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nizna Sunava");
INSERT INTO segments_tester.query_logs_correct VALUES ("Povazska Bystrica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Horny Mostenec");
INSERT INTO segments_tester.query_logs_correct VALUES ("Stupne");
INSERT INTO segments_tester.query_logs_correct VALUES ("Marikova");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hatne");
INSERT INTO segments_tester.query_logs_correct VALUES ("Presov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Mocarmany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Bogdanovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Ploske");
INSERT INTO segments_tester.query_logs_correct VALUES ("Varhanovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Visnie Mirkovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kapusany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vagas");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lada");
INSERT INTO segments_tester.query_logs_correct VALUES ("Meretica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Bajerov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kostolany nad Hor.");
INSERT INTO segments_tester.query_logs_correct VALUES ("Mala Vieska");
INSERT INTO segments_tester.query_logs_correct VALUES ("Budimir");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lemesany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Drienov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Chabazany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Licartovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velky Saris");
INSERT INTO segments_tester.query_logs_correct VALUES ("Maly Saris");
INSERT INTO segments_tester.query_logs_correct VALUES ("Sarisske Luky");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nizny Sebes");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kelemes");
INSERT INTO segments_tester.query_logs_correct VALUES ("Tubrina");
INSERT INTO segments_tester.query_logs_correct VALUES ("Cervenica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Solivar");
INSERT INTO segments_tester.query_logs_correct VALUES ("Solna Bana");
INSERT INTO segments_tester.query_logs_correct VALUES ("Prievidza");
INSERT INTO segments_tester.query_logs_correct VALUES ("Cigel");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kos");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velka Lihotka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Bojnice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kocurany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Novaky");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hornie Lelovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nitrianske Rudno");
INSERT INTO segments_tester.query_logs_correct VALUES ("Liestany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kostolna Ves");
INSERT INTO segments_tester.query_logs_correct VALUES ("Oslany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hornia Ves");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dolny Kamenec");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zemianske Kostolany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Raztocno");
INSERT INTO segments_tester.query_logs_correct VALUES ("Puchov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Strezenice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Cerveny Kamen");
INSERT INTO segments_tester.query_logs_correct VALUES ("Mikusovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zubak");
INSERT INTO segments_tester.query_logs_correct VALUES ("Pruske");
INSERT INTO segments_tester.query_logs_correct VALUES ("Tuchnica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dulov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Bohunice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Luky");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lysa pod Makytou");
INSERT INTO segments_tester.query_logs_correct VALUES ("Revuca");
INSERT INTO segments_tester.query_logs_correct VALUES ("Revucka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Mokra Luka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Moranska Zdychava");
INSERT INTO segments_tester.query_logs_correct VALUES ("Muran");
INSERT INTO segments_tester.query_logs_correct VALUES ("Muranska Lehota");
INSERT INTO segments_tester.query_logs_correct VALUES ("Mur. Dl. Luka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kamenany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Rakes");
INSERT INTO segments_tester.query_logs_correct VALUES ("Rybnik");
INSERT INTO segments_tester.query_logs_correct VALUES ("Spanie Pole");
INSERT INTO segments_tester.query_logs_correct VALUES ("Sasa");
INSERT INTO segments_tester.query_logs_correct VALUES ("Liptovska Tepla");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vlasky");
INSERT INTO segments_tester.query_logs_correct VALUES ("Ivachnova");
INSERT INTO segments_tester.query_logs_correct VALUES ("Liptovska Stiavnica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Stiavnicka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Sliace");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zemanska Ludrova");
INSERT INTO segments_tester.query_logs_correct VALUES ("Turik");
INSERT INTO segments_tester.query_logs_correct VALUES ("Gombas");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lubochna");
INSERT INTO segments_tester.query_logs_correct VALUES ("Sabinov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Marsany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Soma");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nizny Colgory ???");
INSERT INTO segments_tester.query_logs_correct VALUES ("Tolcemes");
INSERT INTO segments_tester.query_logs_correct VALUES ("Plavec nad Popradom");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lubotin");
INSERT INTO segments_tester.query_logs_correct VALUES ("Ujak");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vislanka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Michalany nad Torysou");
INSERT INTO segments_tester.query_logs_correct VALUES ("Gergelak");
INSERT INTO segments_tester.query_logs_correct VALUES ("Medzany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Uzovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Terna");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zatkovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velky Slivnik");
INSERT INTO segments_tester.query_logs_correct VALUES ("Maly Slivnik");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hradisko");
INSERT INTO segments_tester.query_logs_correct VALUES ("Balpotok");
INSERT INTO segments_tester.query_logs_correct VALUES ("Pecovska Nova Ves");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hanigovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Jakovany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lutina");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lipiany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dubovica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dacov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kriviany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Roskoviany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Brezovica nad Tor.");
INSERT INTO segments_tester.query_logs_correct VALUES ("Blazov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hamborek");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nizny Slavkov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Stelbach");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vysoka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Jablonica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hradiste pod Vratnom");
INSERT INTO segments_tester.query_logs_correct VALUES ("Osuske");
INSERT INTO segments_tester.query_logs_correct VALUES ("Sandorf");
INSERT INTO segments_tester.query_logs_correct VALUES ("Cacov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kovalov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Straze nad Myjavou");
INSERT INTO segments_tester.query_logs_correct VALUES ("Cary");
INSERT INTO segments_tester.query_logs_correct VALUES ("Smolinske");
INSERT INTO segments_tester.query_logs_correct VALUES ("Sabotiste");
INSERT INTO segments_tester.query_logs_correct VALUES ("Castkov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Borsky Svaty Mikulas");
INSERT INTO segments_tester.query_logs_correct VALUES ("Borsky Svaty Peter");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kunov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hlboke");
INSERT INTO segments_tester.query_logs_correct VALUES ("Prietrz");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lietnice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Radosovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Cropov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vieska");
INSERT INTO segments_tester.query_logs_correct VALUES ("Unin");
INSERT INTO segments_tester.query_logs_correct VALUES ("Radimov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Spisska Nova Ves");
INSERT INTO segments_tester.query_logs_correct VALUES ("Smizany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Markusovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Jamnik");
INSERT INTO segments_tester.query_logs_correct VALUES ("Koterbachy");
INSERT INTO segments_tester.query_logs_correct VALUES ("Porac");
INSERT INTO segments_tester.query_logs_correct VALUES ("Spisske  Vlachy");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zehra");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hrabusice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Betlanovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vydrnik");
INSERT INTO segments_tester.query_logs_correct VALUES ("Spisske. Tomasovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Spissky Hrusov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hincovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Chrast nad Hornadom");
INSERT INTO segments_tester.query_logs_correct VALUES ("Krompachy");
INSERT INTO segments_tester.query_logs_correct VALUES ("Niznie Slovinky");
INSERT INTO segments_tester.query_logs_correct VALUES ("Visnie Slovinky");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hotkovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Stara Lubovna");
INSERT INTO segments_tester.query_logs_correct VALUES ("Jakubiany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Pilkov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Granastov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Maly Lipnik");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velky Sulin");
INSERT INTO segments_tester.query_logs_correct VALUES ("Starina");
INSERT INTO segments_tester.query_logs_correct VALUES ("Plavnica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Gronos");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hajtovka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Sanbron");
INSERT INTO segments_tester.query_logs_correct VALUES ("Stropkov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Ticinec");
INSERT INTO segments_tester.query_logs_correct VALUES ("Sandal");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kolbovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Chotca");
INSERT INTO segments_tester.query_logs_correct VALUES ("Brusnica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Breznica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Krajna Polana");
INSERT INTO segments_tester.query_logs_correct VALUES ("Bodruzal");
INSERT INTO segments_tester.query_logs_correct VALUES ("Sucha");
INSERT INTO segments_tester.query_logs_correct VALUES ("Sarbov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Krajna Porubka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Medvedzie");
INSERT INTO segments_tester.query_logs_correct VALUES ("Pstrina");
INSERT INTO segments_tester.query_logs_correct VALUES ("Krajna Bystra");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nizny Komarnik");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vysny Komarnik");
INSERT INTO segments_tester.query_logs_correct VALUES ("Potoky");
INSERT INTO segments_tester.query_logs_correct VALUES ("Gribov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velke Bukovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vislava");
INSERT INTO segments_tester.query_logs_correct VALUES ("Duplin");
INSERT INTO segments_tester.query_logs_correct VALUES ("Krusinec");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velkrop");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nizna Olsava");
INSERT INTO segments_tester.query_logs_correct VALUES ("Turiany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Mrazovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Tokajik");
INSERT INTO segments_tester.query_logs_correct VALUES ("Visna Olsava");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lomne");
INSERT INTO segments_tester.query_logs_correct VALUES ("Visny Svidnik");
INSERT INTO segments_tester.query_logs_correct VALUES ("Niznia Jedlova");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nizny Svidnik");
INSERT INTO segments_tester.query_logs_correct VALUES ("Visnia Jedlova");
INSERT INTO segments_tester.query_logs_correct VALUES ("Strocin");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kapisov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vysnia Pisana");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kruzlova");
INSERT INTO segments_tester.query_logs_correct VALUES ("Svidnicka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vapenik");
INSERT INTO segments_tester.query_logs_correct VALUES ("Iadomirova");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hunkovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Krajne Carno");
INSERT INTO segments_tester.query_logs_correct VALUES ("Semetkovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hrabovcik");
INSERT INTO segments_tester.query_logs_correct VALUES ("Rakovcik");
INSERT INTO segments_tester.query_logs_correct VALUES ("Mlynarovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Mestisko");
INSERT INTO segments_tester.query_logs_correct VALUES ("Rovne");
INSERT INTO segments_tester.query_logs_correct VALUES ("Visny Orlik");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nizny Orlik");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vysny Mirosov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Roztoky");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kosarovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Girovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kelca");
INSERT INTO segments_tester.query_logs_correct VALUES ("Giglovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Holcikovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Valkov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Petejovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velka Domasa");
INSERT INTO segments_tester.query_logs_correct VALUES ("Trebisov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hardiste");
INSERT INTO segments_tester.query_logs_correct VALUES ("Maly Ruskov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velky Ruskov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Secovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Backov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zbehnov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Trnavka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kraviany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vojcice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Horovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Miglesov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hriadky");
INSERT INTO segments_tester.query_logs_correct VALUES ("Stanca");
INSERT INTO segments_tester.query_logs_correct VALUES ("Upor");
INSERT INTO segments_tester.query_logs_correct VALUES ("Uhorsky Zipov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velaty");
INSERT INTO segments_tester.query_logs_correct VALUES ("Baranc");
INSERT INTO segments_tester.query_logs_correct VALUES ("Klecenov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lastovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velke Ozorovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nemsova");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hornie Srnie");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hornia Suca");
INSERT INTO segments_tester.query_logs_correct VALUES ("Liborce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Orechove");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zlatovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hanzlikova");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zamarovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Melcice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Ivanovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Strvtok");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zemianske Lieskove");
INSERT INTO segments_tester.query_logs_correct VALUES ("Bosaca");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zem. Pohradie");
INSERT INTO segments_tester.query_logs_correct VALUES ("Trencanska Tepla");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dobra");
INSERT INTO segments_tester.query_logs_correct VALUES ("Tovarniky");
INSERT INTO segments_tester.query_logs_correct VALUES ("Jacovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kuzmice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nemcice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Urmince");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velke Bielice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Skacany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hradiste");
INSERT INTO segments_tester.query_logs_correct VALUES ("Bosany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Krnca");
INSERT INTO segments_tester.query_logs_correct VALUES ("Horne Obdiekovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hornie Stitany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nadlice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Rajcany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Prasice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Podhradie");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zavada");
INSERT INTO segments_tester.query_logs_correct VALUES ("Valasovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Preselany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lasovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hrusovany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zabokreky nad Nitrou");
INSERT INTO segments_tester.query_logs_correct VALUES ("Male Bialice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kovarce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Solcany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Sulovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nitrianska Streda");
INSERT INTO segments_tester.query_logs_correct VALUES ("Oponice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Smolenice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nestich");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dolnie Dubove");
INSERT INTO segments_tester.query_logs_correct VALUES ("Boleraz");
INSERT INTO segments_tester.query_logs_correct VALUES ("Klcovany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dehtice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Katlovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dolna Krupa");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nahac");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dolna Streda nad Vahom");
INSERT INTO segments_tester.query_logs_correct VALUES ("Gan");
INSERT INTO segments_tester.query_logs_correct VALUES ("Horne Oresany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Dolne Oresany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Farkasin");
INSERT INTO segments_tester.query_logs_correct VALUES ("Opoj");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nadas");
INSERT INTO segments_tester.query_logs_correct VALUES ("Biksard");
INSERT INTO segments_tester.query_logs_correct VALUES ("Pusty Fedymes");
INSERT INTO segments_tester.query_logs_correct VALUES ("Pald");
INSERT INTO segments_tester.query_logs_correct VALUES ("Biely Kostol");
INSERT INTO segments_tester.query_logs_correct VALUES ("Pobelnik");
INSERT INTO segments_tester.query_logs_correct VALUES ("Bukovina");
INSERT INTO segments_tester.query_logs_correct VALUES ("Podskolie");
INSERT INTO segments_tester.query_logs_correct VALUES ("Podvlk");
INSERT INTO segments_tester.query_logs_correct VALUES ("Oravka");
INSERT INTO segments_tester.query_logs_correct VALUES ("Srnie");
INSERT INTO segments_tester.query_logs_correct VALUES ("Tvrdosin");
INSERT INTO segments_tester.query_logs_correct VALUES ("Liesek");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vitanova");
INSERT INTO segments_tester.query_logs_correct VALUES ("Sucha Hora");
INSERT INTO segments_tester.query_logs_correct VALUES ("Turany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nolcovo");
INSERT INTO segments_tester.query_logs_correct VALUES ("Ratkovo");
INSERT INTO segments_tester.query_logs_correct VALUES ("Sucany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Priekopa");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lipovec");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zaborie");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kostany nad Turcom");
INSERT INTO segments_tester.query_logs_correct VALUES ("Trebasovo");
INSERT INTO segments_tester.query_logs_correct VALUES ("Necpaly");
INSERT INTO segments_tester.query_logs_correct VALUES ("Bela");
INSERT INTO segments_tester.query_logs_correct VALUES ("Diviaky");
INSERT INTO segments_tester.query_logs_correct VALUES ("Laclava");
INSERT INTO segments_tester.query_logs_correct VALUES ("Slovenske Pravno");
INSERT INTO segments_tester.query_logs_correct VALUES ("Rudno");
INSERT INTO segments_tester.query_logs_correct VALUES ("Pribovce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Rokovo");
INSERT INTO segments_tester.query_logs_correct VALUES ("Benice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Danova");
INSERT INTO segments_tester.query_logs_correct VALUES ("Stavnik");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hvozdnica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hricovske Pohradie");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zlate Moravce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Knazice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Kolenany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zlatno");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nemcicany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Nova Ves nad Zitavou");
INSERT INTO segments_tester.query_logs_correct VALUES ("Male Hydnice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Male Vozokany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Velke Vozokany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Tesary nad Zitavou");
INSERT INTO segments_tester.query_logs_correct VALUES ("Mlynany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Vieska nad Zitavou");
INSERT INTO segments_tester.query_logs_correct VALUES ("Slepcany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Topolcianky");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hoske  ?");
INSERT INTO segments_tester.query_logs_correct VALUES ("Skyvov  ?");
INSERT INTO segments_tester.query_logs_correct VALUES ("Obyce");
INSERT INTO segments_tester.query_logs_correct VALUES ("Jedlove Kostolany");
INSERT INTO segments_tester.query_logs_correct VALUES ("Neverice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Ladice");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hajniky");
INSERT INTO segments_tester.query_logs_correct VALUES ("Rybary");
INSERT INTO segments_tester.query_logs_correct VALUES ("Hronska Breznica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Rajec");
INSERT INTO segments_tester.query_logs_correct VALUES ("Zbynov");
INSERT INTO segments_tester.query_logs_correct VALUES ("Klace");
INSERT INTO segments_tester.query_logs_correct VALUES ("Budatin");
INSERT INTO segments_tester.query_logs_correct VALUES ("Chlumec nad Vahom");
INSERT INTO segments_tester.query_logs_correct VALUES ("Lietavska Lutca");
INSERT INTO segments_tester.query_logs_correct VALUES ("Bytcica");
INSERT INTO segments_tester.query_logs_correct VALUES ("Strecna");
INSERT INTO segments_tester.query_logs_correct VALUES ("Turo");
INSERT INTO segments_tester.query_logs_correct VALUES ("Trnove");
INSERT INTO segments_tester.query_logs_correct VALUES ("Koska");
INSERT INTO segments_tester.query_logs_correct VALUES ("Ustredna Zidov list of workers and associates (?)");
