DROP TABLE IF EXISTS `query_logs_correct`;
CREATE TABLE `query_logs_correct` (
  `query` varchar(200) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;


INSERT INTO query_logs_correct VALUES ('tura luka');
INSERT INTO query_logs_correct VALUES ('myto pod dumbierom');
INSERT INTO query_logs_correct VALUES ('brezno nad hronom');
INSERT INTO query_logs_correct VALUES ('handlova');
INSERT INTO query_logs_correct VALUES ('varin');
INSERT INTO query_logs_correct VALUES ('secovce');
INSERT INTO query_logs_correct VALUES ('plavnica');
INSERT INTO query_logs_correct VALUES ('dezerice');
INSERT INTO query_logs_correct VALUES ('bogdanovce');
INSERT INTO query_logs_correct VALUES ('parnica');
INSERT INTO query_logs_correct VALUES ('zakopcie');
INSERT INTO query_logs_correct VALUES ('udavske');
INSERT INTO query_logs_correct VALUES ('bijacovce');
INSERT INTO query_logs_correct VALUES ('lubenik');
INSERT INTO query_logs_correct VALUES ('solosnica');
INSERT INTO query_logs_correct VALUES ('maly lipnik');
INSERT INTO query_logs_correct VALUES ('banka');
INSERT INTO query_logs_correct VALUES ('nemce');
INSERT INTO query_logs_correct VALUES ('svaty kriz nad hronom');
INSERT INTO query_logs_correct VALUES ('snina');
INSERT INTO query_logs_correct VALUES ('batovce');
INSERT INTO query_logs_correct VALUES ('medzilaborce');
INSERT INTO query_logs_correct VALUES ('modry kamen');
INSERT INTO query_logs_correct VALUES ('boleraz');
INSERT INTO query_logs_correct VALUES ('prasice');
INSERT INTO query_logs_correct VALUES ('dovalovo');
INSERT INTO query_logs_correct VALUES ('kozarovce');
INSERT INTO query_logs_correct VALUES ('modranka');
INSERT INTO query_logs_correct VALUES ('selce');
INSERT INTO query_logs_correct VALUES ('piarg');
INSERT INTO query_logs_correct VALUES ('okruhle');
INSERT INTO query_logs_correct VALUES ('priekopa');
INSERT INTO query_logs_correct VALUES ('svaty ondrej nad hronom');
INSERT INTO query_logs_correct VALUES ('lom nad hronom');
INSERT INTO query_logs_correct VALUES ('pohorela');
INSERT INTO query_logs_correct VALUES ('sered');
INSERT INTO query_logs_correct VALUES ('dolny kubin');
INSERT INTO query_logs_correct VALUES ('havaj');
INSERT INTO query_logs_correct VALUES ('nadas');
INSERT INTO query_logs_correct VALUES ('horne obdiekovce');
INSERT INTO query_logs_correct VALUES ('gnazda');
INSERT INTO query_logs_correct VALUES ('sielnica');
INSERT INTO query_logs_correct VALUES ('mnisek nad popradom');
INSERT INTO query_logs_correct VALUES ('horne byhymcine');
INSERT INTO query_logs_correct VALUES ('busevce');
INSERT INTO query_logs_correct VALUES ('gocovo');
INSERT INTO query_logs_correct VALUES ('malacky');
INSERT INTO query_logs_correct VALUES ('hajniky');
INSERT INTO query_logs_correct VALUES ('rakova');
INSERT INTO query_logs_correct VALUES ('ruzomberok');
