INSERT INTO query_logs_mispelled VALUES ('draluca');
INSERT INTO query_logs_mispelled VALUES ('mytopodumbium');
INSERT INTO query_logs_mispelled VALUES ('resnonadhoran');
INSERT INTO query_logs_mispelled VALUES ('handlava');
INSERT INTO query_logs_mispelled VALUES ('varen');
INSERT INTO query_logs_mispelled VALUES ('sichas');
INSERT INTO query_logs_mispelled VALUES ('plavnica');
INSERT INTO query_logs_mispelled VALUES ('deseres');
INSERT INTO query_logs_mispelled VALUES ('baglnav');
INSERT INTO query_logs_mispelled VALUES ('pernica');
INSERT INTO query_logs_mispelled VALUES ('zacaniv');
INSERT INTO query_logs_mispelled VALUES ('udapskis');
INSERT INTO query_logs_mispelled VALUES ('vagav');
INSERT INTO query_logs_mispelled VALUES ('lubenic');
INSERT INTO query_logs_mispelled VALUES ('selnicka');
INSERT INTO query_logs_mispelled VALUES ('melipniv');
INSERT INTO query_logs_mispelled VALUES ('banka');
INSERT INTO query_logs_mispelled VALUES ('numz');
INSERT INTO query_logs_mispelled VALUES ('sedagriznahavov');
INSERT INTO query_logs_mispelled VALUES ('snidva');
INSERT INTO query_logs_mispelled VALUES ('badoffs');
INSERT INTO query_logs_mispelled VALUES ('medlavoc');
INSERT INTO query_logs_mispelled VALUES ('modrycavin');
INSERT INTO query_logs_mispelled VALUES ('bolderiz');
INSERT INTO query_logs_mispelled VALUES ('brasis');
INSERT INTO query_logs_mispelled VALUES ('dovlavo');
INSERT INTO query_logs_mispelled VALUES ('cozraf');
INSERT INTO query_logs_mispelled VALUES ('modranika');
INSERT INTO query_logs_mispelled VALUES ('sells');
INSERT INTO query_logs_mispelled VALUES ('pirag');
INSERT INTO query_logs_mispelled VALUES ('okrula');
INSERT INTO query_logs_mispelled VALUES ('priecopa');
INSERT INTO query_logs_mispelled VALUES ('sea;klefjsdf');
INSERT INTO query_logs_mispelled VALUES ('lom na hadronan');
INSERT INTO query_logs_mispelled VALUES ('borahela');
INSERT INTO query_logs_mispelled VALUES ('sirdge');
INSERT INTO query_logs_mispelled VALUES ('do na cuban');
INSERT INTO query_logs_mispelled VALUES ('horalig');
INSERT INTO query_logs_mispelled VALUES ('na daas');
INSERT INTO query_logs_mispelled VALUES ('por na dekavas');
INSERT INTO query_logs_mispelled VALUES ('nasda');
INSERT INTO query_logs_mispelled VALUES ('sie hiena');
INSERT INTO query_logs_mispelled VALUES ('nas nad dumas');
INSERT INTO query_logs_mispelled VALUES ('hornbiensin');
INSERT INTO query_logs_mispelled VALUES ('binafs');
INSERT INTO query_logs_mispelled VALUES ('gokovo');
INSERT INTO query_logs_mispelled VALUES ('meloche');
INSERT INTO query_logs_mispelled VALUES ('hajamaley');
INSERT INTO query_logs_mispelled VALUES ('racava');
INSERT INTO query_logs_mispelled VALUES ('ruzumbarak');
INSERT INTO query_logs_mispelled VALUES ('Deraluka');
INSERT INTO query_logs_mispelled VALUES ('Mytipodiberum');
INSERT INTO query_logs_mispelled VALUES ('resnonaturhorin');
INSERT INTO query_logs_mispelled VALUES ('handliva');
INSERT INTO query_logs_mispelled VALUES ('veran');
INSERT INTO query_logs_mispelled VALUES ('sickhavs');
INSERT INTO query_logs_mispelled VALUES ('plavlika');
INSERT INTO query_logs_mispelled VALUES ('disaris');
INSERT INTO query_logs_mispelled VALUES ('baghdinoffs');
INSERT INTO query_logs_mispelled VALUES ('pernika');
INSERT INTO query_logs_mispelled VALUES ('zacopvce');
INSERT INTO query_logs_mispelled VALUES ('udabskees');
INSERT INTO query_logs_mispelled VALUES ('vitokovs');
INSERT INTO query_logs_mispelled VALUES ('lu benick');
INSERT INTO query_logs_mispelled VALUES ('saliznivka');
INSERT INTO query_logs_mispelled VALUES ('mayelipnik');
INSERT INTO query_logs_mispelled VALUES ('bankha');
INSERT INTO query_logs_mispelled VALUES ('nemse');
INSERT INTO query_logs_mispelled VALUES ('svedekrapnivin');
INSERT INTO query_logs_mispelled VALUES ('snahna');
INSERT INTO query_logs_mispelled VALUES ('badops');
INSERT INTO query_logs_mispelled VALUES ('medzlaborse');
INSERT INTO query_logs_mispelled VALUES ('mad rockhamin');
INSERT INTO query_logs_mispelled VALUES ('bowlerez');
INSERT INTO query_logs_mispelled VALUES ('precise');
INSERT INTO query_logs_mispelled VALUES ('dovalavo');
INSERT INTO query_logs_mispelled VALUES ('kozliovse');
INSERT INTO query_logs_mispelled VALUES ('modranka');
INSERT INTO query_logs_mispelled VALUES ('celse');
INSERT INTO query_logs_mispelled VALUES ('paiyarg');
INSERT INTO query_logs_mispelled VALUES ('okarula');
INSERT INTO query_logs_mispelled VALUES ('prehicopa');
INSERT INTO query_logs_mispelled VALUES ('svadirangeorgnaturin');
INSERT INTO query_logs_mispelled VALUES ('lam natur horonom');
INSERT INTO query_logs_mispelled VALUES ('blahirila');
INSERT INTO query_logs_mispelled VALUES ('zcirud');
INSERT INTO query_logs_mispelled VALUES ('donikruben');
INSERT INTO query_logs_mispelled VALUES ('havach');
INSERT INTO query_logs_mispelled VALUES ('naduse');
INSERT INTO query_logs_mispelled VALUES ('hornadikovce');
INSERT INTO query_logs_mispelled VALUES ('nasta');
INSERT INTO query_logs_mispelled VALUES ('saheilnika');
INSERT INTO query_logs_mispelled VALUES ('nazinagdiperdum');
INSERT INTO query_logs_mispelled VALUES ('horm bin en sin');
INSERT INTO query_logs_mispelled VALUES ('binsevs');
INSERT INTO query_logs_mispelled VALUES ('kolkivo');
INSERT INTO query_logs_mispelled VALUES ('melakie');
INSERT INTO query_logs_mispelled VALUES ('pagaeniky');
INSERT INTO query_logs_mispelled VALUES ('rackiva');
INSERT INTO query_logs_mispelled VALUES ('ruzambirak');
INSERT INTO query_logs_mispelled VALUES ('duraluka');
INSERT INTO query_logs_mispelled VALUES ('my tapa dumbirum');
INSERT INTO query_logs_mispelled VALUES ('resnonadhornim');
INSERT INTO query_logs_mispelled VALUES ('hand lava');
INSERT INTO query_logs_mispelled VALUES ('verin');
INSERT INTO query_logs_mispelled VALUES ('zickovs');
INSERT INTO query_logs_mispelled VALUES ('plavnica');
INSERT INTO query_logs_mispelled VALUES ('diserus');
INSERT INTO query_logs_mispelled VALUES ('badanavs');
INSERT INTO query_logs_mispelled VALUES ('pernica');
INSERT INTO query_logs_mispelled VALUES ('zechovsei');
INSERT INTO query_logs_mispelled VALUES ('youdavskies');
INSERT INTO query_logs_mispelled VALUES ('vjokovs');
INSERT INTO query_logs_mispelled VALUES ('lubenic');
INSERT INTO query_logs_mispelled VALUES ('solovsnika');
INSERT INTO query_logs_mispelled VALUES ('malilipnik');
INSERT INTO query_logs_mispelled VALUES ('bangka');
INSERT INTO query_logs_mispelled VALUES ('numvse');
INSERT INTO query_logs_mispelled VALUES ('svadisomeothershit');
INSERT INTO query_logs_mispelled VALUES ('svnana');
INSERT INTO query_logs_mispelled VALUES ('badovs');
INSERT INTO query_logs_mispelled VALUES ('metsalavores');
INSERT INTO query_logs_mispelled VALUES ('mod ri keymen');
INSERT INTO query_logs_mispelled VALUES ('boloraz');
INSERT INTO query_logs_mispelled VALUES ('prosice');
INSERT INTO query_logs_mispelled VALUES ('dovalavo');
INSERT INTO query_logs_mispelled VALUES ('coseroce');
INSERT INTO query_logs_mispelled VALUES ('moldranka');
INSERT INTO query_logs_mispelled VALUES ('cells');
INSERT INTO query_logs_mispelled VALUES ('piarg');
INSERT INTO query_logs_mispelled VALUES ('okay rula');
INSERT INTO query_logs_mispelled VALUES ('praicolpa');
INSERT INTO query_logs_mispelled VALUES ('svadia ');
INSERT INTO query_logs_mispelled VALUES ('lumnadraloham');
INSERT INTO query_logs_mispelled VALUES ('lrehela');
INSERT INTO query_logs_mispelled VALUES ('ciered');
INSERT INTO query_logs_mispelled VALUES ('donikubin');
INSERT INTO query_logs_mispelled VALUES ('phavage');
INSERT INTO query_logs_mispelled VALUES ('notis');
INSERT INTO query_logs_mispelled VALUES ('hornadikavs');
INSERT INTO query_logs_mispelled VALUES ('nasta');
INSERT INTO query_logs_mispelled VALUES ('szihilnika');
INSERT INTO query_logs_mispelled VALUES ('nazicksomething');
INSERT INTO query_logs_mispelled VALUES ('horbehimsign');
INSERT INTO query_logs_mispelled VALUES ('bimzivs');
INSERT INTO query_logs_mispelled VALUES ('gokivo');
INSERT INTO query_logs_mispelled VALUES ('melake');
INSERT INTO query_logs_mispelled VALUES ('hajamiky');
INSERT INTO query_logs_mispelled VALUES ('rakiva');
INSERT INTO query_logs_mispelled VALUES ('rusombirak');
INSERT INTO query_logs_mispelled VALUES ('Darulika');
INSERT INTO query_logs_mispelled VALUES ('Mytapadumbirum');
INSERT INTO query_logs_mispelled VALUES ('Bresnadheronom ');
INSERT INTO query_logs_mispelled VALUES ('Hadlova');
INSERT INTO query_logs_mispelled VALUES ('verin');
INSERT INTO query_logs_mispelled VALUES ('sakovs');
INSERT INTO query_logs_mispelled VALUES ('plavinuka');
INSERT INTO query_logs_mispelled VALUES ('desers');
INSERT INTO query_logs_mispelled VALUES ('vaglanoves');
INSERT INTO query_logs_mispelled VALUES ('burnica');
INSERT INTO query_logs_mispelled VALUES ('zacopicy');
INSERT INTO query_logs_mispelled VALUES ('udavskis');
INSERT INTO query_logs_mispelled VALUES ('vajoscovs');
INSERT INTO query_logs_mispelled VALUES ('lubenic');
INSERT INTO query_logs_mispelled VALUES ('salzinika');
INSERT INTO query_logs_mispelled VALUES ('malulipnic');
INSERT INTO query_logs_mispelled VALUES ('banka');
INSERT INTO query_logs_mispelled VALUES ('nuncs');
INSERT INTO query_logs_mispelled VALUES ('sad he griz nad hernon');
INSERT INTO query_logs_mispelled VALUES ('czan');
INSERT INTO query_logs_mispelled VALUES ('badoves');
INSERT INTO query_logs_mispelled VALUES ('metslavborse');
INSERT INTO query_logs_mispelled VALUES ('modracamen');
INSERT INTO query_logs_mispelled VALUES ('bulraz');
INSERT INTO query_logs_mispelled VALUES ('procize');
INSERT INTO query_logs_mispelled VALUES ('dovlavo');
INSERT INTO query_logs_mispelled VALUES ('coznorof');
INSERT INTO query_logs_mispelled VALUES ('modranka');
INSERT INTO query_logs_mispelled VALUES ('selfs');
INSERT INTO query_logs_mispelled VALUES ('piarg');
INSERT INTO query_logs_mispelled VALUES ('okrarula');
INSERT INTO query_logs_mispelled VALUES ('priecopa');
INSERT INTO query_logs_mispelled VALUES ('sa he underge nad he hermon');
INSERT INTO query_logs_mispelled VALUES ('la nad heronom');
INSERT INTO query_logs_mispelled VALUES ('baherala');
INSERT INTO query_logs_mispelled VALUES ('cierd');
INSERT INTO query_logs_mispelled VALUES ('done e cuban');
INSERT INTO query_logs_mispelled VALUES ('havarge');
INSERT INTO query_logs_mispelled VALUES ('nadus');
INSERT INTO query_logs_mispelled VALUES ('horndevcofs');
INSERT INTO query_logs_mispelled VALUES ('nasda');
INSERT INTO query_logs_mispelled VALUES ('sianoica');
INSERT INTO query_logs_mispelled VALUES ('');
INSERT INTO query_logs_mispelled VALUES ('maz icnac perdhum');
INSERT INTO query_logs_mispelled VALUES ('horne behymnice');
INSERT INTO query_logs_mispelled VALUES ('gocavo');
INSERT INTO query_logs_mispelled VALUES ('malikey');
INSERT INTO query_logs_mispelled VALUES ('hadganikey');
INSERT INTO query_logs_mispelled VALUES ('rakivoa');
INSERT INTO query_logs_mispelled VALUES ('ruzomburik');
INSERT INTO query_logs_mispelled VALUES ('Touraluca');
INSERT INTO query_logs_mispelled VALUES ('maitupa dumbirum');
INSERT INTO query_logs_mispelled VALUES ('bresno nad haronem');
INSERT INTO query_logs_mispelled VALUES ('handleva');
INSERT INTO query_logs_mispelled VALUES ('verin');
INSERT INTO query_logs_mispelled VALUES ('sichavs');
INSERT INTO query_logs_mispelled VALUES ('plavnika');
INSERT INTO query_logs_mispelled VALUES ('dzeris');
INSERT INTO query_logs_mispelled VALUES ('bagdenovs');
INSERT INTO query_logs_mispelled VALUES ('pernica');
INSERT INTO query_logs_mispelled VALUES ('zeycopse');
INSERT INTO query_logs_mispelled VALUES ('uedavscies');
INSERT INTO query_logs_mispelled VALUES ('vgakovs');
INSERT INTO query_logs_mispelled VALUES ('lubenec');
INSERT INTO query_logs_mispelled VALUES ('salovsnika');
INSERT INTO query_logs_mispelled VALUES ('melie lipnick');
INSERT INTO query_logs_mispelled VALUES ('baanka');
INSERT INTO query_logs_mispelled VALUES ('nums');
INSERT INTO query_logs_mispelled VALUES ('svedy griznav heronem');
INSERT INTO query_logs_mispelled VALUES ('sznana');
INSERT INTO query_logs_mispelled VALUES ('badovs');
INSERT INTO query_logs_mispelled VALUES ('metzolaborce');
INSERT INTO query_logs_mispelled VALUES ('mod ray caymen');
INSERT INTO query_logs_mispelled VALUES ('bowleraz');
INSERT INTO query_logs_mispelled VALUES ('prosais');
INSERT INTO query_logs_mispelled VALUES ('doveloveau');
INSERT INTO query_logs_mispelled VALUES ('kozleravs');
INSERT INTO query_logs_mispelled VALUES ('modranka');
INSERT INTO query_logs_mispelled VALUES ('silce');
INSERT INTO query_logs_mispelled VALUES ('pieargh');
INSERT INTO query_logs_mispelled VALUES ('okaerula');
INSERT INTO query_logs_mispelled VALUES ('praicopa');
INSERT INTO query_logs_mispelled VALUES ('sveidy an durg na hrunem');
INSERT INTO query_logs_mispelled VALUES ('lam nad hronom');
INSERT INTO query_logs_mispelled VALUES ('boherella');
INSERT INTO query_logs_mispelled VALUES ('siurd');
INSERT INTO query_logs_mispelled VALUES ('dolny cuban');
INSERT INTO query_logs_mispelled VALUES ('havage');
INSERT INTO query_logs_mispelled VALUES ('nadus');
INSERT INTO query_logs_mispelled VALUES ('hornob di caves');
INSERT INTO query_logs_mispelled VALUES ('nasta');
INSERT INTO query_logs_mispelled VALUES ('sahilnika');
INSERT INTO query_logs_mispelled VALUES ('mna zuck nad hopurnum');
INSERT INTO query_logs_mispelled VALUES ('horn bihem cine');
INSERT INTO query_logs_mispelled VALUES ('bimzvs');
INSERT INTO query_logs_mispelled VALUES ('gokevo');
INSERT INTO query_logs_mispelled VALUES ('melachy');
INSERT INTO query_logs_mispelled VALUES ('hajenacky');
INSERT INTO query_logs_mispelled VALUES ('rackeva');
INSERT INTO query_logs_mispelled VALUES ('rusam birak');
